version: '3.8'

services:
  mail-service:
    container_name: mail-service
    build:
      context: .
    environment:
      - APP_SMTP_PORT=1025
      - APP_SMTP_HOST=smtp-relay
    depends_on:
      - smtp-relay
    ports:
      - 3000:3000
    restart: unless-stopped
  smtp-relay:
    # This would be an actual SMTP relay in production
    image: axllent/mailpit
    container_name: smtp-relay
    restart: unless-stopped
    # volumes:
    #   - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    expose:
      - "8025"
    environment:
      MP_MAX_MESSAGES: 5000
      # MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  # Monitoring
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9091:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - '3050:3000'
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: {}
